### ISSUE TITLE
Update bindings to latest WinRT Api

### ISSUE THREAD

**Issue by oguzhane** [zzl/go-winrtapi#2]
Thank you for providing bindings for WinRT Api.
it seems current bindings are out-of-date, that not including latest api. i.e. [windows.applicationmodel.datatransfer.clipboard.clear](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.clipboard.clear?view=winrt-22621)

it would be really great to regenerate the bindings up-to-date WinRT api.
Thanks

**Comment by zzl** [comment]
The Clear method of the Clipboard class is a static method, which is not supported in Go. In the current API binding implementation, you should create the relevant static objects and then invoke methods on them. I've added a clipboard example to demonstrate this; please check if it helps.

**Comment by oguzhane** [comment]
Thanks @zzl for swift turn around, appreciated!
I just tried it out. It indeed works for me. Closing the issue, then!
